"updates":
- "directory": "/"
  "package-ecosystem": "gomod"
  "schedule":
    "interval": "daily"
- "directory": "/"
  "package-ecosystem": "github-actions"
  "schedule":
    "interval": "daily"
- "directory": "/providers/registry.terraform.io/datadog/datadog"
  "package-ecosystem": "terraform"
  "schedule":
    "interval": "daily"
- "directory": "/providers/registry.terraform.io/pagerduty/pagerduty"
  "package-ecosystem": "terraform"
  "schedule":
    "interval": "daily"
- "directory": "/providers/registry.terraform.io/goauthentik/authentik"
  "package-ecosystem": "terraform"
  "schedule":
    "interval": "daily"
- "directory": "/providers/registry.terraform.io/grafana/grafana"
  "package-ecosystem": "terraform"
  "schedule":
    "interval": "daily"
- "directory": "/providers/registry.terraform.io/hashicorp/archive"
  "package-ecosystem": "terraform"
  "schedule":
    "interval": "daily"
- "directory": "/providers/registry.terraform.io/hashicorp/assert"
  "package-ecosystem": "terraform"
  "schedule":
    "interval": "daily"
- "directory": "/providers/registry.terraform.io/hashicorp/aws"
  "package-ecosystem": "terraform"
  "schedule":
    "interval": "daily"
- "directory": "/providers/registry.terraform.io/hashicorp/azurerm"
  "package-ecosystem": "terraform"
  "schedule":
    "interval": "daily"
- "directory": "/providers/registry.terraform.io/hashicorp/cloudinit"
  "package-ecosystem": "terraform"
  "schedule":
    "interval": "daily"
- "directory": "/providers/registry.terraform.io/hashicorp/dns"
  "package-ecosystem": "terraform"
  "schedule":
    "interval": "daily"
- "directory": "/providers/registry.terraform.io/hashicorp/external"
  "package-ecosystem": "terraform"
  "schedule":
    "interval": "daily"
- "directory": "/providers/registry.terraform.io/hashicorp/google"
  "package-ecosystem": "terraform"
  "schedule":
    "interval": "daily"
- "directory": "/providers/registry.terraform.io/hashicorp/http"
  "package-ecosystem": "terraform"
  "schedule":
    "interval": "daily"
- "directory": "/providers/registry.terraform.io/hashicorp/kubernetes"
  "package-ecosystem": "terraform"
  "schedule":
    "interval": "daily"
- "directory": "/providers/registry.terraform.io/hashicorp/local"
  "package-ecosystem": "terraform"
  "schedule":
    "interval": "daily"
- "directory": "/providers/registry.terraform.io/hashicorp/null"
  "package-ecosystem": "terraform"
  "schedule":
    "interval": "daily"
- "directory": "/providers/registry.terraform.io/hashicorp/random"
  "package-ecosystem": "terraform"
  "schedule":
    "interval": "daily"
- "directory": "/providers/registry.terraform.io/hashicorp/tfe"
  "package-ecosystem": "terraform"
  "schedule":
    "interval": "daily"
- "directory": "/providers/registry.terraform.io/hashicorp/tfmigrate"
  "package-ecosystem": "terraform"
  "schedule":
    "interval": "daily"
- "directory": "/providers/registry.terraform.io/hashicorp/time"
  "package-ecosystem": "terraform"
  "schedule":
    "interval": "daily"
- "directory": "/providers/registry.terraform.io/hashicorp/tls"
  "package-ecosystem": "terraform"
  "schedule":
    "interval": "daily"
- "directory": "/providers/registry.terraform.io/integrations/github"
  "package-ecosystem": "terraform"
  "schedule":
    "interval": "daily"
- "directory": "/providers/registry.terraform.io/kreuzwerker/docker"
  "package-ecosystem": "terraform"
  "schedule":
    "interval": "daily"
- "directory": "/providers/registry.terraform.io/logzio/logzio"
  "package-ecosystem": "terraform"
  "schedule":
    "interval": "daily"
- "directory": "/providers/registry.terraform.io/marcbran/dolt"
  "package-ecosystem": "terraform"
  "schedule":
    "interval": "daily"
- "directory": "/providers/registry.terraform.io/marcbran/jsonnet"
  "package-ecosystem": "terraform"
  "schedule":
    "interval": "daily"
- "directory": "/providers/registry.terraform.io/newrelic/newrelic"
  "package-ecosystem": "terraform"
  "schedule":
    "interval": "daily"
"version": 2