"jobs":
  "push":
    "name": "Push"
    "runs-on": "ubuntu-latest"
    "steps":
    - "uses": "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0"
    - "uses": "hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e"
    - "uses": "extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3"
    - "uses": "actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e"
      "with":
        "cache": true
        "go-version-file": "go.mod"
    - "uses": "jaxxstorm/action-install-gh-release@25e24d2d23ae098373794ef1d6faecb48ee52da8"
      "with":
        "repo": "marcbran/jpoet"
    - "name": "Set Git config"
      "run": |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
    - "env":
        "GIT_PRIVATE_KEY": "${{ secrets.GIT_PRIVATE_KEY }}"
      "name": "Push"
      "run": "just push-provider ./providers/registry.terraform.io/kreuzwerker/docker"
    "timeout-minutes": 5
"name": "Push registry.terraform.io/kreuzwerker/docker"
"on":
  "push":
    "branches":
    - "main"
    "paths":
    - "internal"
    - "providers/registry.terraform.io/kreuzwerker/docker/**"
  "workflow_dispatch": {}
"permissions":
  "contents": "read"