"jobs":
  "test":
    "name": "Test"
    "runs-on": "ubuntu-latest"
    "steps":
    - "uses": "actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8"
    - "uses": "hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd"
    - "uses": "extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff"
    - "uses": "actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00"
      "with":
        "cache": true
        "go-version-file": "go.mod"
    - "uses": "jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2"
      "with":
        "repo": "marcbran/jpoet"
    - "name": "Run tests"
      "run": "just gen-provider ./providers/registry.terraform.io/hashicorp/http"
    "timeout-minutes": 5
"name": "Test registry.terraform.io/hashicorp/http"
"on":
  "pull_request":
    "paths":
    - "internal"
    - "providers/registry.terraform.io/hashicorp/http/**"
  "workflow_dispatch": {}
"permissions":
  "contents": "read"